import React from 'react';
import { Cart } from '@/components';

export const metadata = {
  title: 'Cart - Ecommerce Demo',
  description: 'Generated by create next app',
};

const CartPage = () => {
  return <Cart />;
};

export default CartPage;
