import React from 'react';
import { SignIn } from '@/components';

export const metadata = {
  title: 'Sign In - Ecommerce Demo',
  description: 'Generated by create next app',
};

const SignInPage = () => {
  return <SignIn />;
};

export default SignInPage;
