import React from 'react';
import { UpdateProfile } from '@/components';

export const metadata = {
  title: 'Update My Profile - Ecommerce Demo',
  description: 'Generated by create next app',
};

const UpdateProfilePage = () => {
  return <UpdateProfile />;
};

export default UpdateProfilePage;
