import React from 'react';
import { NewAddress } from '@/components';

export const metadata = {
  title: 'My Address - Ecommerce Demo',
  description: 'Generated by create next app',
};

const NewAddressPage = () => {
  return <NewAddress />;
};

export default NewAddressPage;
