import '../styles/globals.css';
import { Navbar } from '@/components';

export const metadata = {
	title: 'Go Shopping',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='flex flex-col min-h-screen overflow-x-hidden'>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
