import '../styles/globals.css';
import { Navbar } from '@/components/layouts';

export const metadata = {
  title: 'Ecommerce Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen overflow-x-hidden">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
