import React from 'react';
import { SignUp } from '@/components';

export const metadata = {
  title: 'Sign Up - Ecommerce Demo',
  description: 'Generated by create next app',
};

const SignUpPage = () => {
  return <SignUp />;
};

export default SignUpPage;
