import React from 'react';
import axios from 'axios';
import { Profile } from '@/components';
import { cookies } from 'next/headers';

export const metadata = {
  title: 'My Profile - Ecommerce Demo',
  description: 'Generated by create next app',
};

const getAddresses = async () => {
  const nextCookies = cookies();

  const nextAuthSessionToken = nextCookies.get('next-auth.session-token');

  const { data } = await axios.get(`${process.env.BASE_URL}/api/address`, {
    headers: {
      Cookie: `next-auth.session-token=${nextAuthSessionToken?.value}`,
    },
  });

  return data?.addresses;
};

const ProfilePage = async () => {
  const addresses = await getAddresses();

  return <Profile addresses={addresses} />;
};

export default ProfilePage;
