import React from 'react';
import axios from 'axios';
import { Profile } from '@/components';

export const metadata = {
  title: 'My Profile - Ecommerce Demo',
  description: 'Generated by create next app',
};

const getAddresses = async () => {
  const { data } = await axios.get(`${process.env.BASE_URL}/api/address`);

  return data?.addresses;
};

const ProfilePage = async () => {
  const addresses = await getAddresses();

  return <Profile addresses={addresses} />;
};

export default ProfilePage;
