
import React from "react";
import { Profile } from "@/components";

export const metadata = {
  title: 'My Profile - Ecommerce Demo',
  description: 'Generated by create next app',
};


const ProfilePage =   () => {
  return <Profile />;
};

export default ProfilePage;